using RollingBall.Helpers.Patterns;
using UnityEngine;

namespace RollingBall.Player.Input
{
	/// <summary>
	/// This is an abstract class which you can use to have PlayerInput values.
	/// Was generated by my own tool for Unity : https://github.com/Bdiebeak/Input-System-Interface-Generator.
	/// </summary>
	public abstract class PlayerInputHandler : MonoBehaviourSingleton<PlayerInputHandler>
	{
		public Vector2 MovementValue { get; protected set; }
		public Vector2 LookValue { get; protected set; }
		public bool SprintValue { get; protected set; }
		public bool RestartLevel { get; protected set; }
		public bool ReturnToMainMenu { get; protected set; }

		public abstract void BlockInput();
		public abstract void UnblockInput();
	}
}