namespace RollingBall.Player.Input
{
    /// <summary>
    /// This is an enum class with all Action types from Input Action Map.
    /// Was generated by my own tool for Unity : https://github.com/Bdiebeak/Input-System-Interface-Generator.
    /// </summary>
    public enum PlayerActions
    {
        Movement,
        Look,
        Sprint,
    }
}